require 'rails_helper'

$SUCCESS = 1
$ERR_USER_DOESNT_EXIST = -2
$ERR_CARAVAN_ALREADY_EXISTS = -11
$ERR_CARAVAN_DOESNT_EXIST = -12
$ERR_CARAVAN_USER_ALREADY_EXISTS = -13
$ERR_CARAVAN_USER_DOESNT_EXIST = -14
$ERR_ALREADY_A_HOST = -15

describe Caravan do
end
